
 source 'https://github.com/CocoaPods/Specs.git'
 source 'https://github.com/gzc453645620/PodName02.git'
 source 'https://github.com/gzc453645620/ModuleXib.git'


 platform :ios, '9.0'

target 'HiProgress' do

pod 'AFNetworking'
pod 'PodName02'
pod 'ModuleXib'

end
